[package]
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
license = "AGPL-3.0+"
name = "turbofish"
repository = "https://github.com/jplatte/turbo.fish"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.7.0"
rocket = "0.4.2"

[dependencies.rocket_contrib]
version = "0.4.2"
features = ["tera_templates"]
